
name: CMake

on:
  [push]

env:
  BUILD_TYPE: Release

jobs:

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Unittest
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Unittest
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
  
  build-win:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Unittest
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

  e2e-test-macos:

    runs-on: ${{ matrix.os }}
    
    needs: build-macos

    strategy:
      matrix:
        os: [macos-12, macos-11]

    steps:
    - name: Test
      run: echo "e2e test soon to come"

  e2e-test-linux:

    runs-on: ${{ matrix.os }}
    
    needs: build-linux

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - name: Test
      run: echo "e2e test soon to come"

  e2e-test-windows:

    runs-on: ${{ matrix.os }}
    
    needs: build-win

    strategy:
      matrix:
        os: [windows-2022, windows-2019]

    steps:
    - name: Test
      run: echo "e2e test soon to come"