
name: CMake

on:
  [push]

env:
  BUILD_TYPE: Release

jobs:

  build:
  
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
  # atm this is a unit test, this should really be a e2e test!
  test:

    runs-on: ${{ matrix.os }}
    
    needs: build

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

